# Generated by Django 3.1.14 on 2025-12-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permissioncategory',
            table='core_permission_category',
        ),
        migrations.AlterModelTable(
            name='userpermission',
            table='core_user_permission',
        ),
    ]
