# Generated by Django 3.1.14 on 2025-12-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='department',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
