# Generated by Django 3.1.14 on 2025-12-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20251216_0920'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='core_spermission',
        ),
    ]
