# Generated by Django 3.1.14 on 2025-12-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20251216_0921'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='core_permission',
        ),
    ]
