# Generated by Django 3.1.14 on 2025-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_auto_20251208_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
