# Generated by Django 3.1.14 on 2025-12-10 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20251210_1032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='user_groups',
        ),
        migrations.CreateModel(
            name='UserGroupUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_group_users', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_group_users', to='core_api.usergroup')),
            ],
            options={
                'db_table': 'user_group_users',
            },
        ),
    ]
