# Generated by Django 3.1.14 on 2025-12-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_auto_20251210_1430'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='user_group',
        ),
    ]
