# Generated by Django 3.1.14 on 2025-12-15 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_auto_20251211_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('create', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=True)),
                ('update', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'permission_category',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=True)),
                ('update', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_permissions', to='core_api.permission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_permission',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission', to='core_api.permissioncategory'),
        ),
    ]
