# Generated by Django 3.1.14 on 2025-12-17 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms_created_user', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('sla', models.CharField(max_length=10, null=True)),
                ('keywords', models.TextField(null=True)),
                ('primary_image', models.CharField(max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_type', models.CharField(choices=[('USER', 'USER'), ('TEAM', 'TEAM')], default='USER', max_length=10)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_created_user', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.priority')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.servicetype')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('REQUEST', 'REQUEST')], max_length=255, null=True)),
                ('assignee_type', models.CharField(choices=[('USER', 'USER'), ('TEAM', 'TEAM')], max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('when_to_start', models.CharField(choices=[('IMMEDIATE', 'NOW'), ('LATER', 'LATER')], max_length=255, null=True)),
                ('sla_minutes', models.CharField(max_length=255, null=True)),
                ('patient_id', models.CharField(max_length=60, null=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('ASSIGNED NOT STARTED', 'ASSIGNED NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('PAUSED', 'PAUSED'), ('CLOSED', 'CLOSED')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('unique_id', models.CharField(max_length=30, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_created_user', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.priority')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.rooms')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_updated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.usergroup')),
            ],
            options={
                'db_table': 'workorder',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'workorder_attribute_icons',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute_type', models.CharField(choices=[('ELEMENT', 'ELEMENT'), ('GROUP', 'GROUP')], max_length=20)),
                ('element_type', models.CharField(choices=[('INFORMATION', 'INFORMATION'), ('SERVICES', 'SERVICES'), ('REQUEST_ITEMS', 'REQUEST_ITEMS')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('elment_type', models.CharField(choices=[('INFORMATION', 'INFORMATION'), ('SERVICES', 'SERVICES'), ('REQUEST_ITEMS', 'REQUEST_ITEMS')], max_length=30, null=True)),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('information', models.TextField(null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_created_user', to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributeicons')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workorder_attributes',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorder')),
            ],
            options={
                'db_table': 'workorder_timeline',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('REQUEST', 'REQUEST')], max_length=255, null=True)),
                ('assignee_type', models.CharField(choices=[('USER', 'USER'), ('TEAM', 'TEAM')], max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('when_to_start', models.CharField(choices=[('IMMEDIATE', 'NOW'), ('LATER', 'LATER')], max_length=255, null=True)),
                ('sla_minutes', models.CharField(max_length=255, null=True)),
                ('patient_id', models.CharField(max_length=60, null=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('ASSIGNED NOT STARTED', 'ASSIGNED NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('PAUSED', 'PAUSED'), ('CLOSED', 'CLOSED')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('unique_id', models.CharField(max_length=30, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_temp_created_user', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.priority')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.rooms')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_temp_updated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.usergroup')),
                ('workorder_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes')),
            ],
            options={
                'db_table': 'workorder_temp',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_comments_created_user', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_comments_updated_user', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorder')),
            ],
            options={
                'db_table': 'workorder_comments',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.services')),
            ],
            options={
                'db_table': 'workorder_attribute_services',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeRequestItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_quantity', models.IntegerField(null=True)),
                ('max_quantity', models.IntegerField(null=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes')),
            ],
            options={
                'db_table': 'workorder_attribute_request_items',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_attribute_elements', to='workorder_api.workorderattributes')),
                ('attribute_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_element', to='workorder_api.workorderattributes')),
            ],
            options={
                'db_table': 'workorder_attribute_elements',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='workorder_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes'),
        ),
    ]
