# Generated by Django 3.1.14 on 2025-12-08 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0004_auto_20251208_0523'),
        ('workorder_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attribute_type', models.CharField(choices=[('ELEMENT', 'ELEMENT'), ('GROUP', 'GROUP')], max_length=20)),
                ('element_type', models.CharField(choices=[('INFORMATION', 'INFORMATION'), ('SERVICES', 'SERVICES'), ('REQUEST_ITEMS', 'REQUEST_ITEMS')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('elment_type', models.CharField(choices=[('INFORMATION', 'INFORMATION'), ('SERVICES', 'SERVICES'), ('REQUEST_ITEMS', 'REQUEST_ITEMS')], max_length=30, null=True)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_created_user', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.services')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeRequestItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_quantity', models.IntegerField(null=True)),
                ('max_quantity', models.IntegerField(null=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderAttributeElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_attribute_elements', to='workorder_api.workorderattributes')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_attribute_group', to='workorder_api.workorderattributes')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.services')),
            ],
        ),
    ]
