# Generated by Django 3.1.14 on 2025-12-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0002_workorderattributeelements_workorderattributerequestitems_workorderattributes_workorderattributeserv'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderattributes',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
