# Generated by Django 3.1.14 on 2025-12-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0003_workorderattributes_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workorderattributeelements',
            table='workorder_attribute_elements',
        ),
        migrations.AlterModelTable(
            name='workorderattributerequestitems',
            table='workorder_attribute_request_items',
        ),
        migrations.AlterModelTable(
            name='workorderattributes',
            table='workorder_attributes',
        ),
        migrations.AlterModelTable(
            name='workorderattributeservices',
            table='workorder_attribute_services',
        ),
    ]
