# Generated by Django 3.1.14 on 2025-12-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0004_auto_20251208_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderattributeelements',
            name='group',
        ),
        migrations.RemoveField(
            model_name='workorderattributeelements',
            name='service',
        ),
        migrations.AddField(
            model_name='workorderattributeelements',
            name='attribute_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_element', to='workorder_api.workorderattributes'),
        ),
    ]
