# Generated by Django 3.1.14 on 2025-12-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0005_auto_20251208_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttributeIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workorder_attribute_icons',
            },
        ),
        migrations.AlterField(
            model_name='workorderattributes',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributeicons'),
        ),
    ]
