# Generated by Django 3.1.14 on 2025-12-09 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0006_auto_20251209_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderattributeicons',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
