# Generated by Django 3.1.14 on 2025-12-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0007_auto_20251209_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderattributes',
            name='icon',
        ),
        migrations.DeleteModel(
            name='WorkOrderAttributeIcons',
        ),
    ]
