# Generated by Django 3.1.14 on 2025-12-09 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0008_auto_20251209_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttributeIcons',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'workorder_attribute_icons',
            },
        ),
        migrations.AddField(
            model_name='workorderattributes',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributeicons'),
        ),
    ]
