# Generated by Django 3.1.14 on 2025-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0010_workordertemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertemp',
            name='workorder_type',
            field=models.CharField(choices=[('SERVICE', 'SERVICE'), ('REQUEST', 'REQUEST')], max_length=255, null=True),
        ),
    ]
