# Generated by Django 3.1.14 on 2025-12-11 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0007_auto_20251211_0658'),
        ('workorder_api', '0011_auto_20251211_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertemp',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_temp_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workordertemp',
            name='updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_temp_updated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('REQUEST', 'REQUEST')], max_length=255, null=True)),
                ('assignee_type', models.CharField(choices=[('USER', 'USER'), ('TEAM', 'TEAM')], max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('when_to_start', models.CharField(choices=[('IMMEDIATE', 'NOW'), ('LATER', 'LATER')], max_length=255, null=True)),
                ('sla_minutes', models.CharField(max_length=255, null=True)),
                ('patient_id', models.CharField(max_length=60, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('DRAFT', 'DRAFT'), ('IN-PROGRESS', 'IN-PROGRESS'), ('PAUSED', 'PAUSED'), ('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('unique_id', models.CharField(max_length=30, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_created_user', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.priority')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.rooms')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_updated_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.usergroup')),
                ('workorder_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorderattributes')),
            ],
            options={
                'db_table': 'workorder',
            },
        ),
    ]
