# Generated by Django 3.1.14 on 2025-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_api', '0012_auto_20251211_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('ASSIGNED NOT STARTED', 'ASSIGNED NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('PAUSED', 'PAUSED'), ('CLOSED', 'CLOSED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workordertemp',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('ASSIGNED NOT STARTED', 'ASSIGNED NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('PAUSED', 'PAUSED'), ('CLOSED', 'CLOSED')], max_length=50, null=True),
        ),
    ]
