# Generated by Django 3.1.14 on 2025-12-12 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0007_auto_20251211_0658'),
        ('workorder_api', '0013_auto_20251212_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_comments_created_user', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_comments_updated_user', to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorder')),
            ],
            options={
                'db_table': 'workorder_comments',
            },
        ),
    ]
