# Generated by Django 3.1.14 on 2025-12-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_auto_20251211_0658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder_api', '0014_workordercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core_api.tenant')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workorder_api.workorder')),
            ],
            options={
                'db_table': 'workorder_timeline',
            },
        ),
    ]
